version: '3.8'

services:
  ocr-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Set to empty string for CPU-only mode
    volumes:
      - ./models:/app/models  # Optional: cache models locally
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # CPU-only version (uncomment to use)
  # ocr-app-cpu:
  #   build: .
  #   ports:
  #     - "8502:8501"
  #   environment:
  #     - CUDA_VISIBLE_DEVICES=""
  #   volumes:
  #     - ./models:/app/models
  #   restart: unless-stopped

