version: '3.8'

services:
  ocr-app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /data:/data
    working_dir: /app
    # Keep container running for interactive use
    command: tail -f /dev/null

